function onCreatePost()
    addModifier("beat")
    addModifier("stealth")
    addModifier("vibrate")
    addModifier("mini")
    addModifier("wave")
    addModifier("drunk")
    addModifier("tipsy")
    addModifier("tornado")
    addModifier("bumpy")
    addModifier("bounce")
    addModifier("confusion")
    addModifier("scale")
    addModifier("rotate")
    addModifier("reverse")
    addModifier("boost")
    addModifier("brake")
    addModifier("x")
    addModifier("y")
    addModifier("z")
    addModifier("opponentSwap")

    ease("stealth", 0, 0, 1)
    ease("mini", 0, 30, 1.2)

    ease("mini", 32, 2, 0.5)
    ease("wave", 32, 2, 1, "sineInOut")

    ease("beat", 32, 4, 2)
    ease("stealth", 32, 0, 0)
    ease("stealth", 44, 4, 0)
    ease("vibrate", 0, 1, 0.2)

    ease("tipsy", 64, 4, 1)
    ease("tipsy", 128, 4, 0)
    ease("bumpy", 128, 4, 1, "sineInOut", 1)
    ease("bumpy", 160, 4, 0, "sineInOut", 1)

    ease("opponentSwap", 160, 4, 1, "quadInOut", 1)
    ease("opponentSwap", 224, 4, 0, "quadInOut", 1)

    ease("boost", 224, 2, 150, "sineInOut", 0)
    ease("boost", 256, 2, 200, "sineInOut", 0)
    ease("boost", 352, 2, 0, "sineInOut", 0)

    ease("bounce", 424, 1, 50, "linear", 0)
end
